/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Untuk development di VS Code, gunakan environment variables dari .env.local
// Untuk production di Figma Make, gunakan hardcoded values
export const projectId = import.meta.env?.VITE_SUPABASE_URL 
  ? import.meta.env.VITE_SUPABASE_URL.split('//')[1]?.split('.')[0] 
  : "etvwxarauhbutuxrjqpf";

export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY 
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0dnd4YXJhdWhidXR1eHJqcXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4OTk0MDIsImV4cCI6MjA3OTQ3NTQwMn0.CKqTVWWuPDm-E-3Gw1lSFOZQssuVj8aGjw3GvWgm634";